### ISSUE TITLE
backup-monkey crashes when the Request limit is reached

### ISSUE THREAD

**Issue by fsperling** [Answers4AWS/backup-monkey#11]
When creating or deleting a lot of snapshots backup-monkey crashes when the requests to AWS fail because the request limit is reached.

It should catch the error and try again with a lower rate.

`Traceback (most recent call last):
  File "/usr/local/bin/backup-monkey", line 9, in <module>
    load_entry_point('backup-monkey==1.0.0', 'console_scripts', 'backup-monkey')()
  File "/usr/local/lib/python2.7/dist-packages/backup_monkey-1.0.0-py2.7.egg/backup_monkey/cli.py", line 103, in run
    monkey.remove_old_snapshots()
  File "/usr/local/lib/python2.7/dist-packages/backup_monkey-1.0.0-py2.7.egg/backup_monkey/core.py", line 150, in remove_old_snapshots
    snapshot.delete()
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/ec2/snapshot.py", line 97, in delete
    return self.connection.delete_snapshot(self.id, dry_run=dry_run)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/ec2/connection.py", line 2501, in delete_snapshot
    return self.get_status('DeleteSnapshot', params, verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/connection.py", line 1213, in get_status
    response = self.make_request(action, params, path, verb)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/connection.py", line 1116, in make_request
    return self._mexe(http_request)
  File "/usr/local/lib/python2.7/dist-packages/boto-2.38.0-py2.7.egg/boto/connection.py", line 1028, in _mexe
    raise BotoServerError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 503 Service Unavailable
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>RequestLimitExceeded</Code><Message>Request limit exceeded.</Message></Error></Errors><RequestID>7fba627b-7ab4-4b1f-85a4-cde7193d086b</RequestID></Response>
`

**Comment by fsperling** [comment]
Implemented a simple catching and retry mechanism:
https://github.com/Answers4AWS/backup-monkey/pull/12

**Comment by EricDHS** [comment]
@fsperling I hit the same problem as you, and I have a similar fix which you can find from https://github.com/orionhealth/backup-monkey/commit/abc07e346075f57e79a8856010f7a51747ae0a16. Due to we use splunk which does not allow me commit my fix back to main branch. But maybe you can refer it. 

Thanks,
Welcome any feedback.
